'''
Author: LetMeFly
Date: 2025-12-08 13:22:59
LastEditors: LetMeFly.xyz
LastEditTime: 2025-12-10 22:33:12
'''
from bs4 import BeautifulSoup
from bs4.element import Tag
from datetime import datetime, timedelta
from typing import List
import json
import os
import re

originalCWD = os.getcwd()
os.chdir(os.path.dirname(os.path.abspath(__file__)))


def get1problemInfo(titleSlug: str) -> dict:
    # 首次执行时
    if not hasattr(get1problemInfo, "_inited"):
        print("首次执行get1problemInfo函数")
        with open(os.path.join(originalCWD, 'AllProblems/_map_slug+num+name.json'), 'r', encoding='utf-8') as f:
            get1problemInfo._problemInfo = json.load(f)
        get1problemInfo._inited = True
    info = get1problemInfo._problemInfo.get(titleSlug, {})
    num, name = info
    difficulty_pattern = re.compile(r"(简单|中等|困难)")
    with open(os.path.join(originalCWD, f'AllProblems/{name}/{name}.md'), 'r', encoding='utf-8') as f:
        # 一些文件的第4行为形如tags: [题解, LeetCode, 中等, ]的标签，其中有且仅有一个难度等级（简单、中等、困难），提取之
        for i, line in enumerate(f, start=1):
            if i == 4:
                line4 = line
                break
    difficulty = difficulty_pattern.search(line4).group(1)
    difficulty = {"简单": "easy", "中等": "medium", "困难": "**hard**"}.get(difficulty)
    return (num, name, difficulty)


def get1as(html_name: str) -> list: 
    with open(html_name, 'r', encoding='utf-8') as f:
        html = f.read()
    soup = BeautifulSoup(html, 'lxml')
    div = soup.find('div', {'class': 'grid'})
    a_s = div.find_all('a')
    return a_s

a_s = get1as('recentPerDay_11.html')
a_s = a_s + get1as('recentPerDay_12.html')
a_s: List[Tag] = a_s
# print([a['href'] for a in a_s if a['href']])
# t = '/problems/minimum-time-to-make-rope-colorful/?envType=daily-question&envId=2025-11-03'
# print(t.strip('/problems/'))
# print(t.strip('/problems/').split('/')[0])
# print('ams/m1'.strip('ams/'))
slugs = [a['href'].removeprefix('/problems/').split('/')[0] for a in a_s if a.has_attr('href') and a['href']]
# 不可：slugs = [a['href'].strip('/problems/').split('/')[0] for a in a_s if a['href']]

# 从2025.11.1开始按照格式“> - [ ] 01 - [2048. 下一个更大的数值平衡数](https://leetcode.cn/problems/next-greater-numerically-balanced-number/)  2025.10.24 medium”一个一行
today = datetime(2025, 11, 1)
th = 8
cmds = []
skipList = [2536, 1925, 3217, 2257, 3577]

for slug in slugs:
    th += 1
    date_str = today.strftime('%Y.%m.%d')
    today = today + timedelta(days=1)
    data = get1problemInfo(slug)
    num, name, difficulty = data
    print(f'> - [ ] {str(th).zfill(2)} - [{name}](https://leetcode.cn/problems/{slug}/) {date_str} {difficulty}')
    if int(num) not in skipList:
        cmd = f'gh issue create -t "[newSolution]Who can add 1 more problem of LeetCode {num}" -b "By [recentPerDay.py](https://github.com/LetMeFly666/LeetCode/blob/5088eb0aa55018b45047743985e88936dd0f2b14/tryGoPy/ReLeetcode/recentPerDay.py) using GH on Windows | [{name}](https://leetcode.cn/problems/{slug}) " -l "题解" -a "@me"'
        cmds.append(cmd)

print('\nGenerated by [d8caeb](https://github.com/LetMeFly666/LeetCode/blob/5088eb0aa55018b45047743985e88936dd0f2b14/tryGoPy/ReLeetcode/recentPerDay.py)\'s next version') # 永远跟不上的版本
for cmd in cmds:
    print(cmd)

# cannot gh project create --title "1Problem1Day" --owner LetMeFly666
