class LockingTree {
    init(parent: Array<Int64>) {

    }
    
    func lock(num: Int64, user: Int64): Bool {

    }
    
    func unlock(num: Int64, user: Int64): Bool {

    }
    
    func upgrade(num: Int64, user: Int64): Bool {

    }
}

/**
 * Your LockingTree object will be instantiated and called as such:
 * let obj: LockingTree = LockingTree(parent)
 * let param_1 = obj.lock(num,user)
 * let param_2 = obj.unlock(num,user)
 * let param_3 = obj.upgrade(num,user)
 */