class RandomizedSet {
    init() {

    }
    
    func insert(val: Int64): Bool {

    }
    
    func remove(val: Int64): Bool {

    }
    
    func getRandom(): Int64 {

    }
}

/**
 * Your RandomizedSet object will be instantiated and called as such:
 * let obj: RandomizedSet = RandomizedSet()
 * let param_1 = obj.insert(val)
 * let param_2 = obj.remove(val)
 * let param_3 = obj.getRandom()
 */