class Fancy {
    init() {

    }
    
    func append(val: Int64): Unit {

    }
    
    func addAll(inc: Int64): Unit {

    }
    
    func multAll(m: Int64): Unit {

    }
    
    func getIndex(idx: Int64): Int64 {

    }
}

/**
 * Your Fancy object will be instantiated and called as such:
 * let obj: Fancy = Fancy()
 * obj.append(val)
 * obj.addAll(inc)
 * obj.multAll(m)
 * let param_4 = obj.getIndex(idx)
 */