class TweetCounts {
    init() {

    }
    
    func recordTweet(tweetName: String, time: Int64): Unit {

    }
    
    func getTweetCountsPerFrequency(freq: String, tweetName: String, startTime: Int64, endTime: Int64): ArrayList<Int64> {

    }
}

/**
 * Your TweetCounts object will be instantiated and called as such:
 * let obj: TweetCounts = TweetCounts()
 * obj.recordTweet(tweetName,time)
 * let param_2 = obj.getTweetCountsPerFrequency(freq,tweetName,startTime,endTime)
 */