# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: LetMeFly的LeetCode题解等博客
subtitle: 'LetLeet'
description: LeetCode 题解、解题技巧 力扣题解 技术博客
keywords:
author: LetMeFly
language: zh-CN
timezone: Asia/Shanghai
email: Tisfy@qq.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.tisfy.eu.org/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - README.md
  - 404.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 3
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  plugins:
    - plugin:
        name: markdown-it-katex
        enable: true
    - plugin:
        name: markdown-it-mark
        enable: false
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 0
# https://github.com/alexbruno/hexo-generator-json-content
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
# https://github.com/crimx/hexo-filter-github-emojis
githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  styles:
  localEmojis:
# ## Plugins: 
# # Math Equations Render Support
# math:  # hexo-renderer-pandoc
#   enable: true
#   # Default (true) will load mathjax / katex script on demand.
#   # That is it only render those page which has `mathjax: true` in Front Matter.
#   # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
#   per_page: false
#   engine: mathjax

# 主菜单
# 例子
# home 就是图标的标识 从这里挑选http://fontawesome.io/icons/ 图标，把图标下面的文字替换即可使用
#   text ：显示文本
#   url ： 链接
#   target: 链接的锚点 是否在本站中打开链接

# 主菜单
menu:
  home:
    text: 主 页
    url: /
  archives:
    text: 归 档
    url: /archives
  th-list:
    text: 分 类
    url: /categories
  tags:
    text: 标 签
    url: /tags
  smile-o:
    text: 关 于
    url: /about
# 图标菜单
# 如果您没有微信公众号 您完全可以更改为 其他的链接 比如微博
menu2:
  envelope-o:
    text: Email
    url: mailto:1755811882@qq.com
    target: _parent
  github:
    text: Github
    url: https://github.com/tomotoes
    target: _blank
  weibo:
    text: 微博
    url: https://weibo.com/u/6179399347
    target: _blank

# 必备图片
## 你的头像url
avatar: /img/avatar.jpg
## avatar link
avatar_link: /
## favicon
favicon: /img/favicon.ico
## 微信公众号
wechat: /img/wechat.jpg

# 座右铭
## mymotto:  关闭一言
##  content: 用此内容代替一言
mymotto: false
## content: 我的座右铭

# 网站开启时间
startime: 2022/05/14

# 首页副标题
homesubtitle: 在Web全栈的道路上努力前行...

# 归档页标题
archivestitle: 路漫漫其修远兮

# 标签页标题
tagstitle: 不积小流无以成江海

# 分类页标题
categoriestitle: 不积跬步无以至千里

# 关于页标题
aboutitle: 一个坏掉的番茄 

tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: true
excerpt_length: 175
excerpt_link: 阅读全文 »
mathjax: false
archive_yearly: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢您的鼓励支持！     #打赏回馈话语
  wechat: /img/wechat.png     #微信，关闭设为 false
  alipay: /img/alipay.png     #支付宝，关闭设为 false
  wechatalipay: /img/dog.png  #点击打赏时显示的图片

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启分享
share: true

# Themes: https://hexo.io/themes/
theme: tomotoes

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:LetMeFly666/LeetCode.git
  branch: website
