class RangeModule {
    init() {

    }
    
    func addRange(left: Int64, right: Int64): Unit {

    }
    
    func queryRange(left: Int64, right: Int64): Bool {

    }
    
    func removeRange(left: Int64, right: Int64): Unit {

    }
}

/**
 * Your RangeModule object will be instantiated and called as such:
 * let obj: RangeModule = RangeModule()
 * obj.addRange(left,right)
 * let param_2 = obj.queryRange(left,right)
 * obj.removeRange(left,right)
 */