class ThroneInheritance {
    init(kingName: String) {

    }
    
    func birth(parentName: String, childName: String): Unit {

    }
    
    func death(name: String): Unit {

    }
    
    func getInheritanceOrder(): ArrayList<String> {

    }
}

/**
 * Your ThroneInheritance object will be instantiated and called as such:
 * let obj: ThroneInheritance = ThroneInheritance(kingName)
 * obj.birth(parentName,childName)
 * obj.death(name)
 * let param_3 = obj.getInheritanceOrder()
 */