class AllOne {
    init() {

    }
    
    func inc(key: String): Unit {

    }
    
    func dec(key: String): Unit {

    }
    
    func getMaxKey(): String {

    }
    
    func getMinKey(): String {

    }
}

/**
 * Your AllOne object will be instantiated and called as such:
 * let obj: AllOne = AllOne()
 * obj.inc(key)
 * obj.dec(key)
 * let param_3 = obj.getMaxKey()
 * let param_4 = obj.getMinKey()
 */