class SnapshotArray {
    init(length: Int64) {

    }
    
    func set(index: Int64, val: Int64): Unit {

    }
    
    func snap(): Int64 {

    }
    
    func get(index: Int64, snap_id: Int64): Int64 {

    }
}

/**
 * Your SnapshotArray object will be instantiated and called as such:
 * let obj: SnapshotArray = SnapshotArray(length)
 * obj.set(index,val)
 * let param_2 = obj.snap()
 * let param_3 = obj.get(index,snap_id)
 */