class AnimalShelf {
    init() {

    }
    
    func enqueue(animal: Array<Int64>): Unit {

    }
    
    func dequeueAny(): Array<Int64> {

    }
    
    func dequeueDog(): Array<Int64> {

    }
    
    func dequeueCat(): Array<Int64> {

    }
}

/**
 * Your AnimalShelf object will be instantiated and called as such:
 * let obj: AnimalShelf = AnimalShelf()
 * obj.enqueue(animal)
 * let param_2 = obj.dequeueAny()
 * let param_3 = obj.dequeueDog()
 * let param_4 = obj.dequeueCat()
 */