# 例子
# home 就是图标的标识 从这里挑选http://fontawesome.io/icons/ 图标，把图标下面的文字替换即可使用
#   text ：显示文本
#   url ： 链接
#   target: 链接的锚点 是否在本站中打开链接

# 主菜单
menu:
  home:
    text: 主 页
    url: /
  archives:
    text: 归 档
    url: /archives
  th-list:
    text: 分 类
    url: /categories
  tags:
    text: 标 签
    url: /tags
  smile-o:
    text: 关 于
    url: /about

# 图标菜单
# 如果您没有微信公众号 您完全可以更改为 其他的链接 比如微博
menu2:
  envelope-o:
    text: Email
    url: mailto:1755811882@qq.com
    target: _parent
  github:
    text: Github
    url: https://github.com/tomotoes
    target: _blank
  weibo:
    text: 微博
    url: https://weibo.com/u/6179399347
    target: _blank

# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# favicon
favicon: /img/favicon.ico

# 座右铭
# mymotto:  关闭一言
#  content: 用此内容代替一言
mymotto: false
# content: 我的座右铭

# 网站开启时间
startime: 2017/10/11

# 首页副标题
homesubtitle: 在Web全栈的道路上努力前行

# 归档页标题
archivestitle: 路漫漫其修远兮

# 标签页标题
tagstitle: 不积小流无以成江海

# 分类页标题
categoriestitle: 不积跬步无以至千里

# 关于页标题
aboutitle: 一个坏掉的番茄

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#77AAFF'

# 页面标题
tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: true
excerpt_length: 175
excerpt_link: 阅读全文 »
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title: 感谢您的鼓励支持！     #打赏回馈话语
  wechat: /img/wechat.png     #微信，关闭设为 false
  alipay: /img/alipay.png     #支付宝，关闭设为 false
  wechatalipay: /img/dog.png  #点击打赏时显示的图片

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启搜索
search: true

# 是否开启toc
# toc: true
toc:
  list_number: true  # 是否显示数字排序

# 文章页留言内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 原文链接：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- page.permalink.replace(/index\.html$/, '') %></a>


# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 是否使用 gitment，https://github.com/imsun/gitment
gitment: false
# owner: xxx
# repo: xxx
# client_id: xxx
# client_secret: xxx

gitalk: false
# owner: xxx
# repo: xxx
# client_id: xxx
# client_secret: xxx

# Valine Comment system. https://valine.js.org
valine:
  enable: false # 如果你想使用valine，请将值设置为 true
  appId:  # your leancloud appId
  appKey:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Just go go # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2017

# footer中显示的网址
site: tomotoes.com

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 业精于勤荒于嬉，行成于思毁于随

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_pv: 访问次数：
  site_uv: 访问用户：

# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# Emoji
githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  styles:
  localEmojis:
