class Spreadsheet {
    init(rows: Int64) {

    }
    
    func setCell(cell: String, value: Int64): Unit {

    }
    
    func resetCell(cell: String): Unit {

    }
    
    func getValue(formula: String): Int64 {

    }
}

/**
 * Your Spreadsheet object will be instantiated and called as such:
 * let obj: Spreadsheet = Spreadsheet(rows)
 * obj.setCell(cell,value)
 * obj.resetCell(cell)
 * let param_3 = obj.getValue(formula)
 */