class DinnerPlates {
    init(capacity: Int64) {

    }
    
    func push(val: Int64): Unit {

    }
    
    func pop(): Int64 {

    }
    
    func popAtStack(index: Int64): Int64 {

    }
}

/**
 * Your DinnerPlates object will be instantiated and called as such:
 * let obj: DinnerPlates = DinnerPlates(capacity)
 * obj.push(val)
 * let param_2 = obj.pop()
 * let param_3 = obj.popAtStack(index)
 */