class StockPrice {
    init() {

    }
    
    func update(timestamp: Int64, price: Int64): Unit {

    }
    
    func current(): Int64 {

    }
    
    func maximum(): Int64 {

    }
    
    func minimum(): Int64 {

    }
}

/**
 * Your StockPrice object will be instantiated and called as such:
 * let obj: StockPrice = StockPrice()
 * obj.update(timestamp,price)
 * let param_2 = obj.current()
 * let param_3 = obj.maximum()
 * let param_4 = obj.minimum()
 */