class TextEditor {
    init() {

    }
    
    func addText(text: String): Unit {

    }
    
    func deleteText(k: Int64): Int64 {

    }
    
    func cursorLeft(k: Int64): String {

    }
    
    func cursorRight(k: Int64): String {

    }
}

/**
 * Your TextEditor object will be instantiated and called as such:
 * let obj: TextEditor = TextEditor()
 * obj.addText(text)
 * let param_2 = obj.deleteText(k)
 * let param_3 = obj.cursorLeft(k)
 * let param_4 = obj.cursorRight(k)
 */