class FoodRatings {
    init(foods: Array<String>, cuisines: Array<String>, ratings: Array<Int64>) {

    }
    
    func changeRating(food: String, newRating: Int64): Unit {

    }
    
    func highestRated(cuisine: String): String {

    }
}

/**
 * Your FoodRatings object will be instantiated and called as such:
 * let obj: FoodRatings = FoodRatings(foods, cuisines, ratings)
 * obj.changeRating(food,newRating)
 * let param_2 = obj.highestRated(cuisine)
 */