class FrequencyTracker {
    init() {

    }
    
    func add(number: Int64): Unit {

    }
    
    func deleteOne(number: Int64): Unit {

    }
    
    func hasFrequency(frequency: Int64): Bool {

    }
}

/**
 * Your FrequencyTracker object will be instantiated and called as such:
 * let obj: FrequencyTracker = FrequencyTracker()
 * obj.add(number)
 * obj.deleteOne(number)
 * let param_3 = obj.hasFrequency(frequency)
 */