class BrowserHistory {
    init(homepage: String) {

    }
    
    func visit(url: String): Unit {

    }
    
    func back(steps: Int64): String {

    }
    
    func forward(steps: Int64): String {

    }
}

/**
 * Your BrowserHistory object will be instantiated and called as such:
 * let obj: BrowserHistory = BrowserHistory(homepage)
 * obj.visit(url)
 * let param_2 = obj.back(steps)
 * let param_3 = obj.forward(steps)
 */