class SortedStack {
    init() {

    }
    
    func push(val: Int64): Unit {

    }
    
    func pop(): Unit {

    }
    
    func peek(): Int64 {

    }
    
    func isEmpty(): Bool {

    }
}

/**
 * Your SortedStack object will be instantiated and called as such:
 * let obj: SortedStack = SortedStack()
 * obj.push(val)
 * obj.pop()
 * let param_3 = obj.peek()
 * let param_4 = obj.isEmpty()
 */