[package]
name = "LetMeFly-LeetCode-Codes-letmefly_xyz"
version = "0.1.0"
edition = "2021"

# This tells rust-analyzer that the root of the library is lib.rs
[lib]
path = "lib.rs"

[dependencies]
# Add any common dependencies here if you suspect they are used.
# For now, we can leave it empty or add a few common ones for LeetCode.
# e.g., itertools = "0.10"
lazy_static = "1.4.0"
