class Operations {
    init() {

    }
    
    func minus(a: Int64, b: Int64): Int64 {

    }
    
    func multiply(a: Int64, b: Int64): Int64 {

    }
    
    func divide(a: Int64, b: Int64): Int64 {

    }
}

/**
 * Your Operations object will be instantiated and called as such:
 * let obj: Operations = Operations()
 * let param_1 = obj.minus(a,b)
 * let param_2 = obj.multiply(a,b)
 * let param_3 = obj.divide(a,b)
 */