class Encrypter {
    init(keys: Array<Rune>, values: Array<String>, dictionary: Array<String>) {

    }
    
    func encrypt(word1: String): String {

    }
    
    func decrypt(word2: String): Int64 {

    }
}

/**
 * Your Encrypter object will be instantiated and called as such:
 * let obj: Encrypter = Encrypter(keys, values, dictionary)
 * let param_1 = obj.encrypt(word1)
 * let param_2 = obj.decrypt(word2)
 */