name = "api"
compatibility_date = "2024-12-20"
main = "main.js"

# d1_databases = [
#   { binding = "CALENDAR_DB", database_id = "40bf17b1-b598-4ad2-aad0-860f2b282cee" }  # D1数据库api
# ]

[[d1_databases]]
binding = "CALENDAR_DB"  # 代码中访问的绑定名称
database_id = "40bf17b1-b598-4ad2-aad0-860f2b282cee"  # 生产数据库的 UUID - api
preview_database_id = "40bf17b1-b598-4ad2-aad0-860f2b282cee"  # 本地也直接使用生产数据库了