name = "api"
type = "module"  # 绑定D1数据库的Workers要求必须为模块格式而不能是脚本格式
compatibility_date = "2024-12-09"
main = "main.js"

d1_databases = [
  { binding = "api", database_id = "40bf17b1-b598-4ad2-aad0-860f2b282cee" }
]